server:
  port: 9001
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: motan-client-boot

motan:
  annotation:
    package: com.MotanClientBoot.service
  registry:
    regProtocol: consul
    address: 127.0.0.1:8500
    name: my_consul
    connectTimeout: 40000
  protocol:
      name: motan
#  basicservice:
#      group: I_am_fucking_good
#      application: demo
#      exportPort: 8888
#      accessLog: false
#      shareChannel: true
  basicreferer:
    group: oooooo
    request-timeout: 40000