server:
  port: 9003
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  #    defaultZone: http://10.102.47.236:8761/eureka/
spring:
  application:
    name: motan-service-boot


motan:
  annotation:
    package: com.MotanServiceBoot.service
  registry:
    regProtocol: consul
    address: 127.0.0.1:8500
#    address: 10.102.47.236:8500
    name: my_consul
#    connectTimeout: 40000
  protocol:
      name: motan
  basicservice:
      group: oooooo
      application: demo
      share-channel: true
#      export: 8889
      filter: ServiceFilter
      exportPort: 8777
#      accessLog: false
#      shareChannel: true
#  referer:
#      requestTimeout: 40000